### PR TITLE
Docs/add doc cheat sheet links

### PR DESCRIPTION
**Pull request by PipKat**
Per Landon’s request in the PyAnsys Global AFT on 7/26/23, add links to the PyAEDT cheat sheets from this library's documentation.

Note: This library doesn't reuse the README content in the overall index.rst file for documentation (although I am unsure why it doesn't because the content is basically the same). Regardless, I added a new "Documentation and issues" section in both the README and the overall index.rst file.

### CODE REVIEW

**Comment by PipKat** [comment]
@AlejandroFernandezLuces @ninad-kamat I'm awaiting approval from someone to merge this PR. Thanks!

**Comment by PipKat** [comment]
@RobPasMue This PR has been sitting here for several days with no review/approval. Would you mind reviewing. It simply adds cheat sheet links in "Documentation and issues sections" like the several other PRs I submitted last week. (I'm assuming that Alex and Ninad are out of the office.)

**Review by waltersma — APPROVED** [review]

**Comment by waltersma** [comment]
@RobPasMue , @PipKat , approved.

**Comment by PipKat** [comment]
@waltersma @RobPasMue Thanks, Martin, for approving. I am unable to merge, but I'm not sure why. If one of you could merge this PR, I'd appreciate it!

**Comment by RobPasMue** [comment]
Thank you both! I must have missed this PR - sorry!

**Pull request merged**
